### PR TITLE
 Multiples fixes: 

### PR DESCRIPTION
**Pull request by Geolim4**
- Replaced self class calls by static keyword (allows better class extending)
- Enforced strict comparisons on string
- Safely replaced some double quotes by simple quotes

### CODE REVIEW

**Comment by raiym** [comment]
Dear @Geolim4 please revise your pull request (Instagram.php). I have made all methods that query Instagram servers non-static. 
Endpoints.php seems cool.

**Comment by Geolim4** [comment]
oO
I don't get why I does not got a conflict while merging the origin branch ??

**Comment by Geolim4** [comment]
Ahhh okay...
28adced5b6a0c56d0bbc1ed15d2e57c4383cf420 came later. I'll update it tonight then.

**Comment by raiym** [comment]
@Geolim4 thank you

**Comment by Geolim4** [comment]
Your changes were merged to my Pr :)

**Comment by raiym** [comment]
@Geolim4 thank you for contribution

**Comment by Geolim4** [comment]
You're welcome !

**Pull request merged**
