### PR TITLE
Update Instagram.php

### PR DESCRIPTION
**Pull request by noy87ru**
add new method  getMediasFromFeed

### CODE REVIEW

**Comment by ZipDriver** [comment]
Working fine !

**Comment by rhcarlosweb** [comment]
Unfortunately is for only 12 items right?

**Comment by ZipDriver** [comment]
Stop working tonight. Seems Instagram start blocking JSON data as well.

**Comment by raiym** [comment]
Let's merge it anyway and analyze it down the road. 

@noy87ru thank you for contribution.

**Pull request merged**
