### PR TITLE
Add getPaginateMediasByUserId method with $count parameter

### PR DESCRIPTION
**Pull request by bipycxp**
I created this method from `getPaginateMedias` and added `$count` parameter to it.
I didn't add `$count` parameter to `getPaginateMedias` method for a backward compatibility.

### CODE REVIEW

**Comment by bipycxp** [comment]
*some activity*

**Comment by raiym** [comment]
@bipycxp thank you for contribution. 

Could you please resolve conflicts and update pull request.

**Comment by bipycxp** [comment]
@raiym Done

**Comment by raiym** [comment]
@bipycxp thank you.
merged

**Comment by bipycxp** [comment]
@raiym Can you release updates in new version of the package? It will be helpful for me 🙏🏻

**Pull request merged**
