### PR TITLE
Add ability to mark user activity as read by given timestamp

### PR DESCRIPTION
**Pull request by Archy812**
With setActivityRead($timestamp) we can now mark user activity feed as read

### CODE REVIEW

**Comment by Archy812** [comment]
7e1277f is a big one, to get account stats we should mask client as mobile app and change headers accordingly, so work with headers was moved out to separate class. With it, main Instagram class became a little smaller.

N.B. Not all features was tested after refactoring, there can be regressions!

**Comment by raiym** [comment]
@Archy812 thank you for your contribution. 
We should not fake Android device. This repo is done on top of web client API

**Comment by raiym** [comment]
I believe we could merge `mark read activity commit`. 
And then if stats available in the web client we could also consider to merge it.

**Comment by Archy812** [comment]
Masking as Android device is optional and scraper works as web-client by default  (`$emulateApp = false`). I needed to get all stats from account (and soon will need to get all stats about media), so adding this feature was a better solution, than switching to another library. But it's ok, I can work with forked repo.

**Comment by raiym** [comment]
@Archy812 I understand. Not emulating app is not technical decision. 
If you decide to prepare PR without application emulation it would be great addition, In that case please try to minimize code changes. Thanks.

**Comment by Archy812** [comment]
Ok! I'll send new PR soon 👌

**Pull request closed without merging**
