### PR TITLE
Quick fix to get media loading again

### PR DESCRIPTION
**Pull request by benlumley**

### CODE REVIEW

**Comment by kinkytail** [comment]
thanks, it really helped

**Comment by pgrimaud** [comment]
Confirmed it works ! https://github.com/pgrimaud/instagram-user-feed/issues/44

**Comment by lwiml** [comment]
> Confirmed it works ! [pgrimaud/instagram-user-feed#44](https://github.com/pgrimaud/instagram-user-feed/issues/44)

Also confirmed to work, please merge 😄

**Comment by nilsalexberg** [comment]
Thanks, solved the issue

**Comment by rikless** [comment]
For those who need a fix for production with CI, here is a fork with this PR merged https://packagist.org/packages/rikless/instagram-php-scraper

**Comment by raiym** [comment]
@benlumley thank you for contribution

**Pull request merged**
