### PR TITLE
Change user agent

### PR DESCRIPTION
**Pull request by odeialba**
The current url `https://i.instagram.com/api/v1/users/{userId}/info/` doesn't allow the browser's user agent. This Pull Request changes the user agent to the one of the instagram app in android

### CODE REVIEW

**Comment by YuzuruS** [comment]
LGTM 👍

**Comment by kw190** [comment]
My only concern is that the new user agent is defining non-English locale which may lead to unwanted results

**Comment by beshoo** [comment]
Nop it does not help , the problem related to Proxy , Not user agent

**Comment by oalba** [comment]
@beshoo Check here https://github.com/postaddictme/instagram-php-scraper/issues/544 it worked for everyone

**Comment by Zeitwaechter** [comment]
@kwende are you logged in aswell? 
I seem to get only marginal information back when changing my user agent, see #544 :(

**Comment by beshoo** [comment]
It works if you are login... But if you are logout, nop....

**Comment by 27RU57** [comment]
Is it working right now? I have problems with "account with this username was not found"

**Comment by oalba** [comment]
@27RU57 It is working. That's another problem not related with this one

**Comment by 27RU57** [comment]
> @27RU57 It is working. That's another problem not related with this one

Can you write me an email? I'm looking for a solution for that issue. I think we can cooperate

**Pull request closed without merging**
