### PR TITLE
Psr18

### PR DESCRIPTION
**Pull request by sgdot**

### CODE REVIEW

**Comment by raiym** [comment]
@sgdot thank you for contribution

**Comment by Disputer** [comment]
@sgdot Hi Sergey,
Is it still possible to to get user without auth as it said here: "// If account is public you can query Instagram without auth" ?

**Comment by sgdot** [comment]
@Disputer yes, see examples/getAccountByUsername.php

**Comment by Disputer** [comment]
Thanks! Does it depend on proxy? or It doesn't matter?

**Comment by sgdot** [comment]
I think  It doesn't matter. Do you have a problem with this lib?

**Comment by Disputer** [comment]
Can't get data without auth. I'm trying to solve it. I'll write you later, it's my mistake maybe.

**Comment by Disputer** [comment]
If I use home network I can open public accounts without auth, but if I use server ip, I can't. So I'll try to use proxies.

**Pull request merged**
