### PR TITLE
add video duration to object media

### PR DESCRIPTION
**Pull request by mohsen-farahani**

### CODE REVIEW

**Comment by raiym** [comment]
@mohsen-farahani  could you please remove unnecessary paddings.
I use standard PhpStorm formatting.

**Comment by mohsen-farahani** [comment]
@raiym  please recheck

**Comment by raiym** [comment]
@mohsen-farahani thank you for contribution

**Comment by mohsen-farahani** [comment]
@raiym  Thank You
please add a new tag release, 
I need it :)

**Pull request merged**
