### PR TITLE
getAccount from sharedData

### PR DESCRIPTION
**Pull request by yazhog**
Switch to parsing sharedData from account page

### CODE REVIEW

**Comment by grohsfabian** [comment]
I can confirm this works even with the new changes, thank you :)

**Comment by RobertGrubb** [comment]
I second this logic. After yesterday's temporary block of __a=1 I know for sure this will continue to work. I base that off of the fact that instagram still used this route even after the block, which tells me that they will still place that data in this object, even if they do block the route itself again.

**Comment by UXandre** [comment]
Can confirm it's working for me as well. Thanks!

**Comment by raiym** [comment]
@yazhog thank you for contribution

**Pull request merged**
