### PR TITLE
Working getAccountInfo again

### PR DESCRIPTION
**Pull request by cuchac**
Working authentication with `sessionId`, working `getAccountInfo()`. `getAccount()` does not work.

### CODE REVIEW

**Comment by cuchac** [comment]
All credits go to commenters from https://github.com/postaddictme/instagram-php-scraper/issues/1075

**Comment by raiym** [comment]
@cuchac thank you for contribution!

**Comment by Shellai** [comment]
I have the same problem after updating lib and using getMedias() function.

_Response code is 200: OK.Something went wrong. Please report issue._

**Comment by nuzulr24** [comment]
> 

me too

**Pull request merged**
