### PR TITLE
 Replace Unirest by Guzzle + Add auto retry for failed requests

### PR DESCRIPTION
**Pull request by zeliard91**
Hi,

Since I had some unattended errors with Unirest (SSL errors, XXX remaining bytes to read...) during long crawls and that this project seems abandoned, I've replaced the HTTP requests with Guzzle.

One of the advantages of Guzzle is that it can keep the cookies between requests and that they are automatically stored, so the methods `parseCookies` and `generateHeaders` are now useless.

I have also added a retry mechanism when the requests fail, plus the possibility to have multiple proxies that can be switched in order to avoid rate limitations (#330, #494 ...).

The only downside is the 2 factor authorization : according to my tests, the current implementation do not work as there is no more a `$response->body->checkpoint_url` that can be used to submit a code.

### CODE REVIEW

**Comment by raiym** [comment]
@zeliard91 thank you! 
 this is big change. not sure what to do. 
I prefer to make such big changes myself. 
Need more time to review your contribution.

**Comment by jangrewe** [comment]
@raiym any chance to pick this up again? I really hate those Unirest SSL Errors ;-)

**Comment by raiym** [comment]
@jangrewe discussing it with the team

**Comment by raiym** [comment]
@zeliard91 thank your for PR. 

Do you think it is ready to be merged and released?

**Pull request closed without merging**
