### PR TITLE
Add setCustomCookies method

### PR DESCRIPTION
**Pull request by payamomrani**
Hi

When you login with multi ip instagram detect and warn you 
You can set your own cookie from firefox to bypass Instagram Bot

Firefox Cookie for Instagram something like this : 

`$newCookie = [
            "ig_did"         =>	"88E68394-AF06-4968-87A4-****",
	     "mid"           =>	"XtFTPgALAAGAoOYvjP_****",
	     "shbid"         =>	"6262",
            "shbts"          =>	"1594047690.0***3",
            "sessionid"    =>	"36401019872%*****5",
            "csrftoken"    =>	"VeI80iDT****xd",
            "ds_user_id"   => "364****872",
        ];`

before use Login method you should set custom cookie : 
$instagram->setCustomCookies($newCookie);
$instagram->login();

### CODE REVIEW

**Comment by raiym** [comment]
@payamomrani please add new example into examples folder, so developers could easily understand how to set custom cookies 

thanks

**Comment by payamomrani** [comment]
@raiym i created setCustomCookies.php in Example Folder

Thanks

**Comment by raiym** [comment]
@payamomrani thank you for the contribution

**Comment by mohsen-farahani** [comment]
@payamomrani 

I can not find

`shbid`
`shbts`

in cookie

**Pull request merged**
