### PR TITLE
login bug fix

### PR DESCRIPTION
**Pull request by developedsoftware**
Bug fix for the following issues

#365 
#368

### CODE REVIEW

**Comment by developedsoftware** [comment]
I believe this also fixes issue #373

**Comment by raiym** [comment]
@developedsoftware thank you for contribution

**Comment by zubairsultan786** [comment]
Still having the same issue in login.

**Comment by zubairsultan786** [comment]
Is this permanent solution?

**Comment by developedsoftware** [comment]
It should be yes, what error are you still getting?

**Comment by zubairsultan786** [comment]
Hi @developedsoftware 

Now it's worked actually my instagram account giving suspicious login attempt. I solved this issue then it's worked.

Thank you,

**Comment by zubairsultan786** [comment]
@developedsoftware  Is this Permanent solution?

**Comment by zubairsultan786** [comment]
@developedsoftware  it's giving error on login... what i will do?

**Pull request merged**
