### PR TITLE
Update login url

### PR DESCRIPTION
**Pull request by oalba**
The login wasn't working correctly because the url was wrong. The correct url should be https://www.instagram.com/accounts/login/

### CODE REVIEW

**Comment by carlosjsanchezc** [comment]
Im in a loop asking to checkpoint doing and then asking again somebody know what i have to do?

**Comment by carlosjsanchezc** [comment]
https://www.instagram.com/accounts/login/ is not working for me

**Comment by oalba** [comment]
> https://www.instagram.com/accounts/login/ is not working for me

Then your problem might be different, but this one is the correct url

**Comment by raiym** [comment]
@oalba thank you for contribution

**Pull request merged**
