### PR TITLE
[Hotfix] Correct caption & alt text

### PR DESCRIPTION
**Pull request by congkv**
@raiym 
**Before:**
```php
case 'caption':
    $this->caption = $arr[$prop];
    break;
case 'accessibility_caption':
    $this->caption = $value;
    break;
```
**After:**
```php
case 'caption':
    $this->caption = $arr[$prop];
    break;
case 'accessibility_caption':
    $this->altText = $value;
    break;
```

### CODE REVIEW

**Comment by congkv** [comment]
@raiym We should merge this PR ASAP because it is a serious bug!

**Comment by retrowaver** [comment]
Bump.

**Comment by raiym** [comment]
@congkv thank you for contribution

**Comment by congkv** [comment]
@raiym This is an important update. Can you set new version tag for this update?

**Pull request merged**
