### PR TITLE
temporary solution to receive media information without auth

### PR DESCRIPTION
**Pull request by rhcarlosweb**
Only with this here works, can someone can test ?

### CODE REVIEW

**Comment by ryantbrown** [comment]
This is working! 

I did get `Undefined index: csrftoken` in `Instagram.php` on line `220` but changing it to 
` 'x-csrftoken' => $session['csrftoken'] ?? ''` fixed the problem, though I am not sure that is the right solution.

Can you update the PR with a `csrftoken` fix so other people can test?  I think this should be merged as soon possible.

**Comment by rhcarlosweb** [comment]
> I did get Undefined index: csrftoken in Instagram.php on line 220 but changing it to
'x-csrftoken' => $session['csrftoken'] ?? '' fixed the problem, though I am not sure that is the right solution.

This solution works only for php 7.0+ right? i updated, but if someone runs on 5.6 i don't think is gonna work

**Comment by ryantbrown** [comment]
Ya good point, it should use `isset` instead: 
`'x-csrftoken' => isset($session['csrftoken']) ? $session['csrftoken'] : ''`

**Comment by ryantbrown** [comment]
@rhcarlosweb This is working perfect for me. Thanks.

@raiym is there a better way to handle a missing `csrftoken`? When you make an initial unauthenticated request, there is no `set-cookie` response header so the `csrftoken` is empty. Leaving it blank seems to work but I wonder if it's better to `unset` it entirely.

**Comment by MonoWTF** [comment]
@rhcarlosweb the solution is working but I'm not able to get imageLowResolutionUrl, imageThumbnailUrl, and imageStandardResolutionUrl. The only available is imageHighResolutionUrl

**Comment by rhcarlosweb** [comment]
@MonoWTF i think is related of this issue i post: #329

**Comment by rhcarlosweb** [comment]
@ryantbrown i think the error you get is fix too if added
```
$cookies = self::parseCookies($response->headers['Set-Cookie']);
$this->userSession['csrftoken'] = $cookies['csrftoken'];
```
after response, i notice in the others request have this line after response to get csrftoken

**Comment by ryantbrown** [comment]
@rhcarlosweb ya that makes sense, the `csrftoken` is only available after an initial response.

**Comment by rhcarlosweb** [comment]
solution no longer works, now needs a `$this->userSession['sessionid']` and this is generated by a auth user =\

**Pull request closed without merging**
