### PR TITLE
ErrorException  : Undefined index: Set-Cookie

### PR DESCRIPTION
**Pull request by approached**
Hello,

Exception:
```
   ErrorException  : Undefined index: Set-Cookie

  at /Users/approach/workspace/IALaravel/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:851
    847|         if ($response->code !== 200) {
    848|             throw new InstagramException('Response code is ' . $response->code . '. Body: ' . static::getErrorBody($response->body) . ' Something went wrong. Please report issue.');
    849|         }
    850|
  > 851|         $cookies = static::parseCookies($response->headers['Set-Cookie']);
    852|         $this->userSession['csrftoken'] = $cookies['csrftoken'];
    853|
    854|         $arr = json_decode($response->raw_body, true, 512, JSON_BIGINT_AS_STRING);
    855|

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: Set-Cookie", "/Users/approach/workspace/IALaravel/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php")
      /Users/approach/workspace/IALaravel/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:851
```

Solution: Just send special header, that you accept the cookies. (dsgvo)
Reference issue: #373

### CODE REVIEW

**Comment by mikesteeghs** [comment]
Unfortunately, this doesn't work for me. I'm getting the following response:

```
[InstagramScraper\Exception\InstagramException]
  Response code is 400. Body: <html>
  <head>
  <title>5xx Server Error</title>
  </head>

  <body>
  <h1>5xx Server Error</h1>
  </body>

  </html>
   Something went wrong. Please report issue.
```

**Comment by approached** [comment]
@mikesteeghs: Url, Stacktrace?

**Comment by approached** [comment]
@raiym can you check/merge it?

**Comment by Mehrdad-Dadkhah** [comment]
same problem

**Pull request closed without merging**
